# Generated by Django 3.2.18 on 2023-05-15 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unlike_users',
            field=models.ManyToManyField(related_name='unlike_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
