# Generated by Django 3.2.18 on 2023-05-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20230512_0128'),
        ('communities', '0002_initial'),
    ]

    operations = [
    ]
