# Generated by Django 3.2.18 on 2023-05-15 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_comment_unlike_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='unlike_users',
            field=models.ManyToManyField(related_name='unlike_recomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
