# Generated by Django 3.2.18 on 2023-05-12 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolment_users',
            field=models.ManyToManyField(blank=True, related_name='enrolment_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
